### ISSUE TITLE
Unable to load active_merchant/common

### ISSUE THREAD

**Issue by mikepence** [jpablobr/active_paypal_adaptive_payment#11]
When trying to load my project I get this exception:

no such file to load -- active_merchant/common

I am using:
rails 3.0.10
active_paypal_adaptive_payment 0.1.2

I tried the obvious step of adding a line in my gemfile:

gem "activemerchant", :require => 'active_merchant'

That did not solve the problem.

**Comment by jpablobr** [comment]
`active_paypal_adaptive_payment` already requires `activemerchant`:

https://github.com/jpablobr/active_paypal_adaptive_payment/blob/master/active_paypal_adaptive_payment.gemspec#L18

Have you tried without it? I actually never add the `activemerchant` gem to my apps `Gemfile`.

**Comment by mikepence** [comment]
I got it to work by changing the gemspec to use activemerchange "= 1.5.1", and that fixed it. So, something changed in activemerchant between 1.5.1 and 1.20.4 that was breaking it.

**Comment by jpablobr** [comment]
hmmm ok, I'll check that out. But you are right, `activemerchant` is actually moving quite fast and I gotta keep up with that :D 

I'm closing the issue since you were able to fix it. Thank you for letting me know!

**Comment by mikepence** [comment]
Weird, though, when I forked and pulled the gem source, the version of activemerchant that bundler pulled down was 1.18.1.

**Comment by jpablobr** [comment]
weirder, I'm getting a **Repository temporarily unavailable.** :/

**Comment by mikepence** [comment]
Yeah, I can't push to my fork, right now.
