### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by vinceh** [jpablobr/active_paypal_adaptive_payment#15]
Ruby 1.9.2p180
Rails 3.1.1

In my gemfile `gem 'active_paypal_adaptive_payment'` followed by `bundle install`.  Then `rails s`, and 

```
c:/Ruby192/lib/ruby/gems/1.9.1/gems/activemerchant-1.5.1/lib/active_merchant/lib
/validateable.rb:31:in `<module:Validateable>': uninitialized constant ActiveMer
chant::Validateable::HashWithIndifferentAccess (NameError)
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/activemerchant-1.5.1/lib/active
_merchant/lib/validateable.rb:2:in `<module:ActiveMerchant>'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/activemerchant-1.5.1/lib/active
_merchant/lib/validateable.rb:1:in `<top (required)>'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/activemerchant-1.5.1/lib/active
_merchant.rb:33:in `require'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/activemerchant-1.5.1/lib/active
_merchant.rb:33:in `<top (required)>'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/active_paypal_adaptive_payment-
0.3.8/lib/active_paypal_adaptive_payment.rb:2:in `require'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/active_paypal_adaptive_payment-
0.3.8/lib/active_paypal_adaptive_payment.rb:2:in `<top (required)>'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/bundler-1.1.pre.4/lib/bundler/r
untime.rb:68:in `require'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/bundler-1.1.pre.4/lib/bundler/r
untime.rb:68:in `block (2 levels) in require'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/bundler-1.1.pre.4/lib/bundler/r
untime.rb:66:in `each'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/bundler-1.1.pre.4/lib/bundler/r
untime.rb:66:in `block in require'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/bundler-1.1.pre.4/lib/bundler/r
untime.rb:55:in `each'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/bundler-1.1.pre.4/lib/bundler/r
untime.rb:55:in `require'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/bundler-1.1.pre.4/lib/bundler.r
b:122:in `require'
        from c:/Users/vinceh/Desktop/projects/weeverails/config/application.rb:7
:in `<top (required)>'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.1.1/lib/rails/comman
ds.rb:52:in `require'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.1.1/lib/rails/comman
ds.rb:52:in `block in <top (required)>'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.1.1/lib/rails/comman
ds.rb:49:in `tap'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.1.1/lib/rails/comman
ds.rb:49:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
```

Seems to be coming from the `require`.

**Comment by jpablobr** [comment]
I believe this should do it. Can you try now?

https://github.com/jpablobr/active_paypal_adaptive_payment/commit/ebfdd6fd07f65189f7b7bfb9041e968f6fbef6b4

**Comment by vinceh** [comment]
I uninstalled the gem and did another `bundle install` and I'm still getting the same error.  Or do you want me to download the latest version of the code from GitHub?

**Comment by jpablobr** [comment]
can you try with `gem "active_paypal_adaptive_payment", "~> 0.3.9"` in your Gemfile

**Comment by vinceh** [comment]
Great.  Seems to start now.

Now when I try to make the payment, I get this from PayPal's website:

URL: https://www.sandbox.paypal.com/webscr?cmd=_ap-payment&paykey=
Message: This transaction is invalid. Please return to the recipient's website and try again.

Code inside my controller:

```
gateway =  ActiveMerchant::Billing::PaypalAdaptivePayment.new(
            :login => "npo_1332820242_biz_api1.gmail.com",
            :password => "XXXXXXX", 
            :signature => "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            :appid => "APP-80W284485P519543T" )

        recipients = [{:email => 'admin_1332814369_biz@gmail.com',
                 :amount => 5,
                 :primary => true},
                {:email => 'npo_1332820242_biz@gmail.com',
                 :amount => 10,
                 :primary => false}
                 ]

        response = gateway.setup_purchase(
            :return_url => url_for(:action => :complete, :only_path => false),
            :cancel_url => url_for(:action => :cancel, :only_path => false),
            :ipn_notification_url => url_for(:action => :success, :only_path => false),
            :receiver_list => recipients
        )

        redirect_to (gateway.redirect_url_for(response["payKey"]))
```

Anything you spot right away?

**Comment by jpablobr** [comment]
did you set the test mode in your app?

``` ruby
#config/environments/{environment.rb}
App::Application.configure do
  config.setting...
end
ActiveMerchant::Billing::Base.mode = :test
```

**Comment by vinceh** [comment]
Yup, in both `development.rb` and `production.rb`

I should also probably mention that I'm testing it through Heroku since I can't do it locally, and that's where I'm getting the issue from, but I'm not sure if that has to do with anything.

**Comment by jpablobr** [comment]
I never had any issues like that with heroku. 

Are you using Spree? in that case, the config settings Payment Methods (in admin), the environment should reflect the PayPal environment. For example, in production the server should not be configure to test.

**Comment by vinceh** [comment]
No, I'm not using Spree.

I created a simple application that tests out the functionality of the gem.

The repository is here (I took out the PayPal credentials to the latest commit): [https://github.com/vinceh/testpaypal](https://github.com/vinceh/testpaypal)

And I've hosted on Heroku @ [http://blazing-meadow-5453.herokuapp.com/](http://blazing-meadow-5453.herokuapp.com/)

Do you want to take a look?  The `:test` is in the environments, and it's just copy and pasted code into the controller.  Maybe you can spot something.

**Comment by jpablobr** [comment]
Have you ran the tests? do they run fine? you only have to update this file with your credentials

https://github.com/jpablobr/active_paypal_adaptive_payment/blob/master/test/fixtures.example.yml (remove the example part)

**Comment by vinceh** [comment]
No I have not.  I will try it tomorrow.  But I noticed there is a pay_key attribute.  What is that?  I never specified anything like that in my application; is that the problem?

**Comment by jpablobr** [comment]
See issue #14

https://github.com/jpablobr/active_paypal_adaptive_payment/issues/14

That might help you a bit. And yes, you need the `pay_key`, that's Paypal's first response to your payment request.

**Comment by vinceh** [comment]
I wrapped the redirect_to with 

```
if response.success?
    redirect_to (gateway.redirect_url_for(response[:pay_key]))
end
```

And it seems that my response is not successful.  How do I debug this?

**Comment by jpablobr** [comment]
response.inspect should contain PayPal's response... see what you got there and search for that specific error on PayPals documentation.
