### ISSUE TITLE
Chained payments not working

### ISSUE THREAD

**Issue by marcmp** [jpablobr/active_paypal_adaptive_payment#17]
In a chained payment, using the same example in "README.md" but setting both recipients to ":primary => false" does work.
However setting one to "true" and the other to "false" prompts a paypal web page saying " This transaction is not valid. Go back the the vendor website and try again"

**Comment by jpablobr** [comment]
hmmm which one are you setting to `:primary => false`?

Also, did you set the test mode in your app?

``` Ruby
#config/environments/{environment.rb}
App::Application.configure do
  config.setting...
end
ActiveMerchant::Billing::Base.mode = :test
```

**Comment by marcmp** [comment]
Thanks Jose Pablo,

I'm using the following recipients. Just in case, I've created both test accounts as sellers in my paypal sandbox account:

``` ruby
recipients = [{:email => "seller_1334834068_biz@mac.com",
                    :amount => 4,
                    :primary => true},
                    {:email => "seller_1333898129_biz@mac.com",
                    :amount => 4,
                    :primary => false}]
```

Also the _mode_ is set to _:test_ properly at the end of the environment.rb in `development` (my current environment):
`ActiveMerchant::Billing::Base.mode = :test`

Setting both sellers to `:primary => false` fixes the problem, but I'm not looking for simple but chained payment.

Any other ideas on what could be wrong?

**Comment by marcmp** [comment]
I found out what was going wrong by debugging Paypal's response from setup_purchase call. Adaptative Chained Payments are a lot trickier than simple Adaptative because not everything is permited...

What happened was that Paypal won't accept certain chained adaptative payments. The errors I was given were:
- "The amount for the primary receiver must be greater than or equal to the total of other chained receiver amounts"
- "The receiver seller_1334834068_biz@mac.com does not accept payments in this Currency"
- "Account mac@mac.com is restricted" => This means that we need to create the account for primary sellers

**Comment by jpablobr** [comment]
:hammer: :)
