### ISSUE TITLE
Weird errors on Heroku

### ISSUE THREAD

**Issue by mooktakim** [jpablobr/active_paypal_adaptive_payment#2]
I am using this gem for one of my projects. I'm trying to deploy to Heroku, but the deploy fails with a strange error:

-----> Heroku receiving push
-----> Ruby/Rails app detected
-----> Installing dependencies using Bundler version 1.1.pre.10
       Running: bundle install --without development:test --path vendor/bundle --deployment
       Fetching dependency information from the API at http://rubygems.org/
       Unfortunately, the gem active_paypal_adaptive_payment (0.2.0) has an invalid gemspec. As a result, Bundler cannot install this Gemfile. Please ask the gem author to yank the bad version to fix this issue. For more information, see http://bit.ly/illformed-requirement.
 !
 !     Failed to install gems via Bundler.
 !
 !     Heroku push rejected, failed to compile Ruby/rails app

To git@heroku.com:myapp.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:myapp.git'

It might be that the 0.2.0 version of the gem causing rubygems to break.
Is there anyway to yank that version from rubygems?

**Comment by jpablobr** [comment]
What's on your Gemfile? can you try with:

`gem "active_paypal_adaptive_payment", "~> 0.2.4"`

**Comment by mooktakim** [comment]
I tried the above,
I also tried:

`gem "active_paypal_adaptive_payment", "0.2.4"`

Still doesn't work.

I think its a bundler issue. But heroku hasn't updated to the latest beta version.
bundler has a fix which skips versions that are incorrect, instead of crashing out.

Is there anyway you can remove version 0.2.0 from rubygems?

**Comment by jpablobr** [comment]
yanked... try again :/

**Comment by mooktakim** [comment]
Woohoo!
Works, thanks!

**Comment by jpablobr** [comment]
:zap:
