### ISSUE TITLE
App ID

### ISSUE THREAD

**Issue by michaelboutros** [jpablobr/active_paypal_adaptive_payment#22]
Hello all. I'm using this gem and it wasn't working initially because it required an app ID but PayPal didn't give me one. I changed line 37 of active_paypal_adaptive_payment.rb to not require an app ID and since then things have been gravy. I realize it's a tiny change but I've forked a copy of the repo and will send a pull request shortly!

**Comment by jpablobr** [comment]
Hey thanks, and there's no such a thing as a tiny commit! if it helps the gem I'll merge it :) :sparkles:
