### ISSUE TITLE
What parameters does paypal send back when it redirects to my site?

### ISSUE THREAD

**Issue by hayesmp** [jpablobr/active_paypal_adaptive_payment#28]
How do I verify that the transaction was successful? Or do I just have to rely on whichever callback url it redirects to to know whether it was successful or not?

I am doing chained payments and it is redirecting back to my site using the return_url. Is it trying to send something to my ipn url?

**Comment by jpablobr** [comment]
Most of what you need to know is in the `response` hash sent by PayPal. See:

https://github.com/jpablobr/active_paypal_adaptive_payment#chained-payments

**Comment by hayesmp** [comment]
Is there a response I can grab AFTER the payment has been made?

**Comment by jpablobr** [comment]
With the PayPal's IPN, see:

https://github.com/jpablobr/active_paypal_adaptive_payment/blob/master/lib/active_merchant/billing/integrations/paypal_adaptive_payment/notification.rb

is very similar to the one `active_merchant` is using for PayPal Express.

https://github.com/Shopify/active_merchant/blob/master/lib/active_merchant/billing/integrations/paypal/notification.rb

**Comment by hayesmp** [comment]
The ipn callback doesn't seem to be called in the sandbox..?
