### ISSUE TITLE
Not receiving a response from the IPN when ipn_notification_url is called

### ISSUE THREAD

**Issue by richardsondx** [jpablobr/active_paypal_adaptive_payment#29]
I wasn't able to retrieve the information sfrom the IPN for the confirmations after the payment. Can you provide a guideline for that or a link that can help me figuring it out?

Also, I've implemented "Setting advanced payment and invoice options"  and I'm not sure where exactly the invoice is going? It seem that the information provided there are used to set up the paypal landing page for the item being purchased.

https://gist.github.com/8acceeee72fe12312c09

**Comment by jpablobr** [comment]
Hey, is this the problem you are having?

https://github.com/jpablobr/active_paypal_adaptive_payment/issues/32

**Comment by jpablobr** [comment]
I guess you were able to fix it...

**Comment by richardsondx** [comment]
Sorry for the late reply. I had to test it in production and it worked. Thanks.
