### ISSUE TITLE
:start_time and :end_time for preapproved payments do not include GMT offset

### ISSUE THREAD

**Issue by adamvr** [jpablobr/active_paypal_adaptive_payment#30]
G'day,

Here's a quick and dirty patch to fix it. 

https://gist.github.com/3141560

Thanks for writing this rather handy library!

**Comment by jpablobr** [comment]
Hey, not sure I understand this issue correctly... What do you want me to do?

I mean, is that an issue that is not letting you process the transaction? or a FYI? 

If you want, maybe add this to the `README.md`, send me a pull request, and I'll gladly merge it in. :)

**Comment by jpablobr** [comment]
Hey I'm closing the issue. Feel free to reopen if needed...
