### ISSUE TITLE
its possible send ClientDetails Fields?

### ISSUE THREAD

**Issue by hyperrjas** [jpablobr/active_paypal_adaptive_payment#33]
I wonder if can i send in request fields like **applicationId, customerId, customerType**...etc. You can see in this page https://cms.paypal.com/uk/cgi-bin/?cmd=_render-content&content_ID=developer/e_howto_api_APPreapproval

Thank you very much!

**Comment by jpablobr** [comment]
yeah, it should be possible. That said, not sure if it's implemented already. But it would be a matter of adding to:

https://github.com/jpablobr/active_paypal_adaptive_payment/blob/master/lib/active_merchant/billing/gateways/paypal_adaptive_payment.rb

**Comment by hyperrjas** [comment]
Thank you Pablo, let me know when this functionality is implemented. Thank you very much!

**Comment by hyperrjas** [comment]
Thank you!
