### ISSUE TITLE
parameter=["X-PAYPAL-APPLICATION-ID"] severity="Error" subdomain="Application"> on  production envirnomen.

### ISSUE THREAD

**Issue by jpablobr** [jpablobr/active_paypal_adaptive_payment#5]
[<#Hashie::Rash category="Application" domain="PLATFORM" error_id="560022" message="The X-PAYPAL-APPLICATION-ID header contains an invalid value" parameter=["X-PAYPAL-APPLICATION-ID"] severity="Error" subdomain="Application">]

This is an error that im only getting on Production server, everything works fine on development...

**Comment by arnaud** [comment]
@jpablobr I'm facing the same issue. Could you elaborate on what you did to solve this issue?

**Comment by jpablobr** [comment]
I don't remember quit well, but I belive it was an error due to using production environment setting and combining it with development setting on heroku. If you are testing your app on Heroku maybe PayPal is complaining about the subdomain thing (yourapp.heroku.com). I'll ask a friend who is the one that was actually having the problem and I'll get back to you here.

**Comment by jpablobr** [comment]
@arnaud Yeah, it was a problem with the environments; in the `config/environment/production.rb` be sure to remove `#ActiveMerchant::Billing::Base.mode = :test`

**Comment by arnaud** [comment]
@jpablobr Thanks for the follow-up. The sad thing is that I don't have this line. Well, I may have to submit a stackoverflow post then :)

**Comment by jpablobr** [comment]
@arnaud so, in `development` environment using your test PayPal sandbox credentials it works fine?

Also, in case you are using Spree, in the config settings Payment Methods (in admin), the environment should reflect the PayPal environment. For example, in `production` the server should not be configure to `test`.

**Comment by arnaud** [comment]
It wasn't working on development. And you nailed it: the following line was missing from my `development.rb` file:
`ActiveMerchant::Billing::Base.mode = :test`
Adding this line to `development.rb` did the trick.
Thanks!

**Comment by jpablobr** [comment]
@arnaud cool! glad it worked :)
