### ISSUE TITLE
#setup_purchase response payKey redirects user to wrong url

### ISSUE THREAD

**Issue by jpablobr** [jpablobr/active_paypal_adaptive_payment#6]
When calling `#setup_purchase` the response `payKey` redirects user to `redirect_url_for(response["payKey"].to_s)` url which seems to be incorrect since that's the pay screen, and if the user submits the form, immediate payment is made.

It appears that the users need to be sent to `/webscr?cmd=_ap-preapproval&preapprovalkey=PA-XXX` which in turn will prompt the user with the proper pre-approval form.

**Comment by LeviRosol** [comment]
In an attempt to follow the documentation (https://cms.paypal.com/us/cgi-bin/?cmd=_render-content&content_ID=developer/e_howto_api_APPayAPI in the "Preapproved payment example" section) I have added the preapprovalKey to the Pay post. When submitting that data, a 520002 error is returned (Internal Error). 

'Response: {"responseEnvelope":{"timestamp":"2011-11-09T11:47:11.825-08:00","ack":"Failure","correlationId":"f65f84d1ccbfa","build":"2228340"},"error":[{"errorId":"520002","domain":"PLATFORM","subdomain":"Application","severity":"Error","category":"Application","message":"Internal Error"}]}'

I do have a ticket open with PayPal for further clarification and will update accordingly.

My minor change can be seen in this commit: https://github.com/eliasonmedia/active_paypal_adaptive_payment/commit/ab43e514b6a39ee9347cdcefd03cd08be72af14b#lib/active_merchant/billing/gateways/paypal_adaptive_payment.rb

**Comment by LeviRosol** [comment]
Also, to clarify, the `#setup_purchase` method does work correctly for chained payments. It appears that if the `opts[:preapproval_key]` exists, then the method should return the `_ap-preapproval` url.

**Comment by LeviRosol** [comment]
pull request submitted. #7
