### ISSUE TITLE
Hashie gem conflict

### ISSUE THREAD

**Issue by LeviRosol** [jpablobr/active_paypal_adaptive_payment#8]
I'm not sure how to best fix this, or even figure out what gem dependency is causing this.

My issue is that I have active_paypal_adaptive_payment setup and in use, and am now adding amniauth-facebook to my app. In doing so I ran into a version conflict with the Hashie gem.

`
Bundler could not find compatible versions for gem "hashie":
  In Gemfile:
    active_paypal_adaptive_payment (>= 0) ruby depends on
      hashie (~> 1.0.0) ruby

```
omniauth-facebook (>= 0) ruby depends on
  hashie (1.2.0)
```

`

**Comment by LeviRosol** [comment]
As I was writing this, I found the issue and the fix, however, we need to wait on another repo to be updated, so I created the ticket anyways to serve as a placeholder.

Once https://github.com/tcocca/rash/pull/4 gets merged in, this commit should fix the conflict: https://github.com/eliasonmedia/active_paypal_adaptive_payment/commit/736114187667d4033d33095d79001cd1447b9b2e

If the version of Rash does change, I'll update accordingly.

in the mean time, people can add an entry to their gemfile for:

`gem "rash", :git => "https://github.com/tallgreentree/rash.git", :branch => "bump-hashie-version-dependency"`

**Comment by jpablobr** [comment]
Okay, if you want send me the pull request and I'll merge it and release it including the previews commit.

**Comment by LeviRosol** [comment]
will do once rash is updated.

**Comment by jpablobr** [comment]
I believe this [commit](https://github.com/jpablobr/active_paypal_adaptive_payment/commit/7480424f811d7aa548ffe8be976c2dd03906ffb3) fixes it. Check it out and let me know if you ran into any issue.
